name: deploy

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  pull-code:
    name: ðŸ”„ Pull latest code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH for bot
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Git pull and install dependencies
      run: |
        ssh bot@${{ secrets.SSH_HOST }} << EOF
          cd /home/bot/cicord || exit 1
          git pull origin main

          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi

          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          deactivate
        EOF

  restart-service:
    name: ðŸ” Restart cicord service
    runs-on: ubuntu-latest
    needs: pull-code

    steps:
    - name: Setup SSH for admin
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Restart service as admin
      run: |
        ssh debian@${{ secrets.SSH_HOST }} << EOF
          sudo systemctl restart cicord
        EOF
